name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks-scan:
    name: Analisis de Seguridad Unificado
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Correr Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # NUEVO BLOQUE AGREGADO
      - name: Escaneo de Vulnerabilidades (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      # TRINCHERA 3: Análisis de Código Estático (SAST)
      - name: Auditoria de Codigo Python (Bandit)
        uses: PyCQA/bandit-action@v1
        with:
          # Fallar si encuentra vulnerabilidades de severidad Media o Alta
          severity: 'medium'
          exit_code: 1 # <--- ¡ESTE ES EL COMANDO CRÍTICO!
